#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------


namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Data {
                ref class CollectionViewSource;
            }
        }
    }
}
namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class RelativePanel;
                ref class ScrollViewer;
                ref class TextBlock;
                ref class MediaElement;
                ref class Slider;
                ref class Canvas;
                ref class CaptureElement;
                ref class Button;
                ref class ToggleSwitch;
                ref class ComboBox;
            }
        }
    }
}

namespace PiBotCpp
{
    [::Windows::Foundation::Metadata::WebHostHidden]
    partial ref class MainPage : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector,
        public ::Windows::UI::Xaml::Markup::IComponentConnector2
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
        virtual ::Windows::UI::Xaml::Markup::IComponentConnector^ GetBindingConnector(int connectionId, ::Platform::Object^ target);
    
    private:
        bool _contentLoaded;
    
        private: ::Windows::UI::Xaml::Data::CollectionViewSource^ DeviceListSource;
        private: ::Windows::UI::Xaml::Controls::RelativePanel^ pnMain;
        private: ::Windows::UI::Xaml::Controls::RelativePanel^ pnCommunications;
        private: ::Windows::UI::Xaml::Controls::RelativePanel^ servoPanel;
        private: ::Windows::UI::Xaml::Controls::RelativePanel^ rpLabelsPanel;
        private: ::Windows::UI::Xaml::Controls::RelativePanel^ pnStatus;
        private: ::Windows::UI::Xaml::Controls::ScrollViewer^ scrStatus;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ tbStatus;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ textBlock1;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ textBlock2;
        private: ::Windows::UI::Xaml::Controls::MediaElement^ AudioElement;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ textBlock4;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ textBlock5;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ textBlock6;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ textBlock7;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ textBlock8;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ textBlock11;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ textBlock12;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ textBlock13;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ textBlock14;
        private: ::Windows::UI::Xaml::Controls::Slider^ speedRightHip;
        private: ::Windows::UI::Xaml::Controls::Slider^ accelerationRightHip;
        private: ::Windows::UI::Xaml::Controls::Slider^ servoRightHip;
        private: ::Windows::UI::Xaml::Controls::Slider^ speedRightLeg;
        private: ::Windows::UI::Xaml::Controls::Slider^ accelerationRightLeg;
        private: ::Windows::UI::Xaml::Controls::Slider^ servoRightLeg;
        private: ::Windows::UI::Xaml::Controls::Slider^ speedRightAnkle;
        private: ::Windows::UI::Xaml::Controls::Slider^ accelerationRightAnkle;
        private: ::Windows::UI::Xaml::Controls::Slider^ servoRightAnkle;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ distfoot1;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ tbRightFootDistance;
        private: ::Windows::UI::Xaml::Controls::Slider^ speedLeftHip;
        private: ::Windows::UI::Xaml::Controls::Slider^ accelerationLeftHip;
        private: ::Windows::UI::Xaml::Controls::Slider^ servoLeftHip;
        private: ::Windows::UI::Xaml::Controls::Slider^ speedLeftLeg;
        private: ::Windows::UI::Xaml::Controls::Slider^ accelerationLeftLeg;
        private: ::Windows::UI::Xaml::Controls::Slider^ servoLeftLeg;
        private: ::Windows::UI::Xaml::Controls::Slider^ speedLeftAnkle;
        private: ::Windows::UI::Xaml::Controls::Slider^ accelerationLeftAnkle;
        private: ::Windows::UI::Xaml::Controls::Slider^ servoLeftAnkle;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ distfoot2;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ tbLeftFootDistance;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ tbVoltageLabel;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ Heading2;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ tbHeading2;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ tbBatteryVoltage;
        private: ::Windows::UI::Xaml::Controls::Canvas^ HeadCanvas;
        private: ::Windows::UI::Xaml::Controls::CaptureElement^ headElement;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ tbDistanceLabel;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ Heading;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ tbHeading;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ tbHeadDistance;
        private: ::Windows::UI::Xaml::Controls::Button^ btnGetChannel;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ tbLHS;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ tbLHA;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ tbLHSR;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ tbLLS;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ tbLLA;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ tbLLSR;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ tbLAS;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ tbLAA;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ tbLASR;
        private: ::Windows::UI::Xaml::Controls::ToggleSwitch^ btnCommsConnect;
        private: ::Windows::UI::Xaml::Controls::ComboBox^ cbCommsDevices;
    };
}

